elf2flt.c: add support for SOURCE_DATE_EPOCH
uclinux-dev/elf2flt pull request #13
Opened 2019-12-27 17:17 UTC by tpetazzoni

The bFLT header has a "build_date" field which contains the date/time
at which the bFLT file was created. Unfortunately, this breaks
reproducible builds as two identical builds done at different times
will produce different results.

For example, on a bFLT binary, diffoscope reports the following
change:

  00000000: 6246 4c54 0000 0004 0000 0045 0001 48d4  bFLT.......E..H.
  00000010: 0002 85a0 0002 fe50 0000 1000 0002 85a0  .......P........
 -00000020: 0000 0757 0000 0001 5e05 742e 0000 0000  ...W....^.t.....
 +00000020: 0000 0757 0000 0001 5e05 a5c2 0000 0000  ...W....^.......

In order to address this, this commit adds support for the
SOURCE_DATE_EPOCH environment variable, which is standardized by the
reproducible-builds.org group at
https://reproducible-builds.org/specs/source-date-epoch/.

We simply use the time from the SOURCE_DATE_EPOCH variable (which
contains the number of seconds since Epoch) when SOURCE_DATE_EPOCH is
available in the environment, and otherwise fallback to the existing
logic that takes the current time using time().

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

2019-12-28 04:30 UTC, vapier requested changes
binutils has a `--enable-deterministic-archives` configure flag.  imo we should add a similar `--enable-deterministic-flat` option (and perhaps even default it to true).

there is also a `D` flag to `ar` to control this at runtime.  we could add a `-D` flag to elf2flt to opt-in dynamically.

2019-12-28 04:30 UTC, vapier commented on elf2flt.c
> +  char *sde;
`const char *`

2019-12-28 04:30 UTC, vapier commented on elf2flt.c
> +      t = (time_t) strtoul(sde, NULL, 10);
no space between the cast & func call

is it even needed though ?  let the compiler figure it out ?

2019-12-28 09:41 UTC, tpetazzoni commented
Thanks @vapier for you review. Do we really need a --enable-deterministic-archives compile-time option or a -D runtime option ? For example, gcc obeys to SOURCE_DATE_EPOCH, without any special option (it changes the behavior of the __DATE__ and __TIME__ macros).

2019-12-28 09:45 UTC, vapier commented
i'm not saying we don't support SOURCE_DATE_EPOCH.  your change here (ignoring style nits) is fine.  i'm suggesting we add a configure option for it too.  it can be done in a follow up commit.

2019-12-29 08:59 UTC, yann-morin-1998 commented on elf2flt.c
> +      t = (time_t) strtoul(sde, NULL, 10);
The toolchain wrapper in Buildroot use `strtoll()` and checks for `errno` after the attempted conversion.

2019-12-29 09:09 UTC, yann-morin-1998 commented on elf2flt.c
> +      t = (time_t) strtoul(sde, NULL, 10);
And as usual, reading the [docs](https://reproducible-builds.org/docs/source-date-epoch/) is insightful:
they use `strtoull()`.

2019-12-29 09:35 UTC, tpetazzoni commented
I have pushed another iteration of the patch, which takes into account some of the comments. The (time_t) cast between strtoll() and the time_t variable is still needed, because strtoll will return a "signed long long", but the type of time_t may not necessarily match that.

2019-12-29 09:36 UTC, tpetazzoni commented
Damn, just seen the comment from Yann suggesting to use strtoull(), so I'll do another iteration later.

2019-12-29 13:44 UTC, tpetazzoni commented
Ok, here it comes, a new iteration. Hopefully this one will be good :-)

2019-12-29 14:00 UTC, vapier approved these changes

2019-12-29 14:09 UTC, yann-morin-1998 commented
As far as I'm concerned, this looks goo to me. Thanks. :-)

2019-12-29 14:12 UTC, merged

2019-12-29 14:13 UTC, vapier commented
we really should have a configure flag as i suggested earlier though before 2038 :p

2019-12-29 14:18 UTC, tpetazzoni commented
Warning: I messed up and forgot to git amend before doing my Buildroot build, so I didn't actually test build the latest version. I'll do so later today, and come back with additional fixes if it turns out to be broken. Sorry about this :-/

Why do you think we should have a configure flag before 2038 ? The bFLT header only has 32-bit to store time already and my patch doesn't change anything to that, so the 2038 issue is not related to reproducible builds.

2019-12-29 14:26 UTC, vapier commented
I'm not saying this change makes the situation worst, I'm saying the best way to avoid the overflow is to not use it at all. better to train people earlier rather than later that this field is not reliable so they don't get surprised when it does break.