elf2flt: handle binutils >= 2.34
uclinux-dev/elf2flt pull request #15
Opened 2020-02-12 20:48 UTC by RomainNaour

The latest Binutils release (2.34) is not compatible with elf2flt due
to a change in bfd_section_* macros. The issue has been reported to
the Binutils mailing list but Alan Modra recommend to bundle libbfd
library sources into each projects using it [1]. That's because the
API is not stable over the time without any backward compatibility
guaranties.

On the other hand, the elf2flt tools needs to support modified
version of binutils for specific arch/target [2].

Add two tests in the configure script to detect this API change
in order to support binutils < 2.34 and binutils >= 2.34.

[1] https://sourceware.org/ml/binutils/2020-02/msg00044.html
[2] https://github.com/uclinux-dev/elf2flt/issues/14

Signed-off-by: Romain Naour <romain.naour@smile.fr>

2020-02-13 02:37 UTC, vapier requested changes
some nits

2020-02-13 02:37 UTC, vapier commented on configure.ac
> + bfd_section_size_macro_has_one_arg=yes,
name this more generically like `bfd_section_api_takes_bfd` or something.  they converted all the APIs at once, so there's no need to test each one individually.

2020-02-13 02:37 UTC, vapier commented on elf2flt.c
> +#define elf2flt_bfd_section_size(abs_bfd, s) bfd_section_size(s)
the point of the API change is that the bfd isn't actually used by any of the bfd_section funcs.  so we should structure our API similarly.

```c
#define elf2flt_bfd_section_size(s) bfd_section_size(s)
#else
#define elf2flt_bfd_section_size(s) bfd_section_size(NULL, s)
```

2020-02-13 02:37 UTC, vapier commented on elf2flt.c
> +#if defined(HAVE_BFD_SECTION_SIZE_MACRO_HAS_ONE_ARG)
you can use `#ifdef` here instead

2020-02-13 02:37 UTC, vapier commented on configure.ac
> +dnl Various bfd section macros and functions like bfd_section_size() has been
has->have

2020-02-13 02:37 UTC, vapier commented on configure.ac
> +dnl modified starting binutils >= 2.34.
"starting with binutils"

2020-02-13 02:37 UTC, vapier commented on configure.ac
> +dnl Check if the prototype is "bfd_section_size (sec)" or "bfd_section_size(bfd, ptr)"
"Check if the prototypes take a bfd argument."

2021-08-18 21:37 UTC, vapier commented
were you planning on refreshing this ?

2023-03-08 13:50 UTC, gregungerer commented
This looks to have been sitting here for quite a while now. I have manually resolved the conflict, so it is at least clean and ready to be applied. As far as I can tell Romain addressed all feedback.

2023-03-14 06:34 UTC, vapier commented
tbh, i didn't really notice the updated pushes since the open comments weren't marked resolved, so was waiting for OP to do so.  if you think issues are resolved, and you've rebased the work, then let's merge it.

should update the unittest coverage (i.e. uclinux-dev/prebuilts-binutils-libs) to make sure things work & stay working.

2023-03-22 14:13 UTC, gregungerer commented
Further testing has found at least one problem. This only works if you use the single --with-binutils-build-dir configure form. If you specify each of the --with-libbfd/--with-libiberty/etc configure options (but no --with-binutils-build-dir option) it will fail to detect the version of binutils correctly.

2023-03-22 14:19 UTC, gregungerer commented
Oh, and the in-tree configure script needs to be regenerated too.

2023-03-23 14:59 UTC, vapier commented
hmm, we should add those scenarios to our CI tests

2023-04-04 04:01 UTC, gregungerer commented
This pull request updated to fix --with-binutils-build-dir case and the configure script re-generated and applied to main.

2023-04-04 04:01 UTC, closed without merging