elf2flt: add riscv support
uclinux-dev/elf2flt pull request #19
Opened 2020-09-09 08:35 UTC by damien-lemoal

We need a new linker script - riscv has a global_pointer and is
very picky about some section ordering.

Signed-off-by: Christoph Hellwig <hch@lst.de>
Signed-off-by: Damien Le Moal <damien.lemoal@wdc.com>

2020-09-09 09:22 UTC, vapier reviewed
are you sure you really need a linker script just to provide `global_pointer` ?  we handle this for other targets via -defsym.  look in ld-elf2flt.c for more info.

2020-09-09 09:22 UTC, vapier commented on elf2flt.c
> +#define ARCH    "riscv64"
just put one tab after `ARCH`

2020-09-11 07:38 UTC, damien-lemoal commented
defsym seems to be only when shared libraries are used, but the riscv toolchain does not support -mid-shared-library, so I do not think we can use that. We can only build static libraries. Or am I missing something ? And the linker script also reorders some sections, it is not only about __global_pointer definition.

2020-09-11 09:03 UTC, vapier commented
defsym is for any final link, not just shared libs.  i wouldn't be surprised if you don't (yet?) have support for shared libs as it requires more effort (not all ports even today bother implementing it), so don't worry about it.

static libs are just a bunch of objects.  don't worry about that either.

you still do the final link when creating the program (ELF) that is then converted to the FLAT format.  that's when the linker script comes into play.  so defsym should be usable here.

i grok that your replacement linker script is ordering things differently.  but why ?  "it's picky" isn't really an explanation.  we have more than 10 arch ports that have been able to largely share the linker script, and they all have their own weird quirks.

2020-09-11 09:18 UTC, damien-lemoal commented
OK. So I can try using the defsym thingy for __global_pointer, but I do not really understand hos it works... In binutils, __global_pointer address is:

```__global_pointer$ = MIN(__SDATA_BEGIN__ + 0x800,\n\                         
                            MAX(__DATA_BEGIN__ + 0x800, __BSS_END__ - 0x800));
```
How can I replicate that with defsym ?

As for the section ordering difference, I am not sure. I am a little out of my depth with all this. Need more study. This is Christoph work. The current patch gives me clean runs of busybox with kernels up to 5.8.4, but not after that. This commit:

```commit c05dea7c0f3ff1a8d63b41542c4161406093dc2f
Author: Max Filippov <jcmvbkbc@gmail.com>
Date:   Sat Aug 8 11:37:13 2020 -0700

    binfmt_flat: revert "binfmt_flat: don't offset the data start"
    
    commit 2217b982624680d19a80ebb4600d05c8586c4f96 upstream.
    
    binfmt_flat loader uses the gap between text and data to store data
    segment pointers for the libraries. Even in the absence of shared
    libraries it stores at least one pointer to the executable's own data
    segment. Text and data can go back to back in the flat binary image and
    without offsetting data segment last few instructions in the text
    segment may get corrupted by the data segment pointer.
    
    Fix it by reverting commit a2357223c50a ("binfmt_flat: don't offset the
    data start").
    
    Cc: stable@vger.kernel.org
    Fixes: a2357223c50a ("binfmt_flat: don't offset the data start")
    Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>
    Signed-off-by: Greg Ungerer <gerg@linux-m68k.org>
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
```
Which changes the binflat loader results in a crash (segfault) of the init process (busybox shell). So this current patch is definitely not OK yet, but I cannot yet pinpoint the problem.

2020-09-14 14:09 UTC, gregungerer commented
Hi Daemien,

On 11/9/20 7:19 pm, Damien Le Moal wrote:
> OK. So I can try using the defsym thingy for __global_pointer, but I do 
> not really understand hos it works... In binutils, __global_pointer 
> address is:
> 
> |MAX(__DATA_BEGIN__ + 0x800, __BSS_END__ - 0x800)); |
> 
> How can I replicate that with defsym ?
> 
> As for the section ordering difference, I am not sure. I am a little out 
> of my depth with all this. Need more study. This is Christoph work. The 
> current patch gives me clean runs of busybox with kernels up to 5.8.4, 
> but not after that. This commit:
> 
> |Author: Max Filippov <jcmvbkbc@gmail.com> Date: Sat Aug 8 11:37:13 2020 
> -0700 binfmt_flat: revert "binfmt_flat: don't offset the data start" 
> commit 2217b982624680d19a80ebb4600d05c8586c4f96 upstream. binfmt_flat 
> loader uses the gap between text and data to store data segment pointers 
> for the libraries. Even in the absence of shared libraries it stores at 
> least one pointer to the executable's own data segment. Text and data 
> can go back to back in the flat binary image and without offsetting data 
> segment last few instructions in the text segment may get corrupted by 
> the data segment pointer. Fix it by reverting commit a2357223c50a 
> ("binfmt_flat: don't offset the data start"). Cc: stable@vger.kernel.org 
> Fixes: a2357223c50a ("binfmt_flat: don't offset the data start") 
> Signed-off-by: Max Filippov <jcmvbkbc@gmail.com> Signed-off-by: Greg 
> Ungerer <gerg@linux-m68k.org> Signed-off-by: Greg Kroah-Hartman 
> <gregkh@linuxfoundation.org> |
> 
> Which changes the binflat loader results in a crash (segfault) of the 
> init process (busybox shell). So this current patch is definitely not OK 
> yet, but I cannot yet pinpoint the problem.

FWIW the original patch that this reverted (a2357223c50a) was from 
Christoph. I am guessing he did all this work at the same time?
And that means that the elf2flt layout for riscv probably reflects
what that original commit changed to.

Regards
Greg


> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/uclinux-dev/elf2flt/pull/19#issuecomment-690977641>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAIOZ2EZU37Y5GROWUL7B23SFHTQVANCNFSM4RBQ2ZNQ>.
>

2020-09-15 09:25 UTC, damien-lemoal commented
@gregungerer I am talking with Christoph about this. We will get it sorted. We are both busy at the moment but will get to this as soon as possible. Thanks !

2020-10-30 18:48 UTC, pdp7 commented
@damien-lemoal I'm a little out of my depth here, but I'm interested in making K210 more useful.  Is this an alternative to the FPDIC effort that Maciej gave a talk about?

2020-11-02 01:09 UTC, damien-lemoal commented
@pdp7 I think it is the other way around: FDPIC support is the more advanced solution for NOMMU and is (will be) the alternative to using flatbin format which has been around for a long time now. Flat bin/elf2flt is what we have today that works, modulo the current kernel "problem" mentioned above (not clear yet where the problem is). As for making the K210 more useful, happy to report progress here: See the Linux tree here: https://github.com/damien-lemoal/linux/tree/k210-sysctl-v12. This adds all needed drivers and device tree to have GPIO, I2C and SPI/SD-card working. Userspace can now be stored on the SD card and no initramfs is required. You can see this code in action here, controlling a robot arm through I2C with a SiPeed Dan Dock: https://damien-lemoal.github.io/linux-robot-arm/#example. I will post all the kernel patches very soon after a last round of cleanup.

2021-06-14 00:24 UTC, damien-lemoal commented
Updated this PR. No major changes from the previous version: the riscv linker script is still added (I cannot get anything working without it) but elf2flt.c changes are now cleaner. Comments are welcome ! Thanks.

2021-06-17 23:22 UTC, damien-lemoal commented
Ping ? Any comment ?

2021-08-20 06:25 UTC, vapier requested changes
sorry, but i really really don't want to see another unique linker script.  the expectation normally is for the person submitting new code to find alternatives.

wrt section ordering, this sounds like bugs in the toolchain or kernel.  so i'm expecting those to be resolved elsewhere, not workedaround in elf2flt.

wrt `__global_pointer$`, i've done very little research into this symbol.  iiuc, the value is copied into the `gp` register, and then it's left as a constant for the life of the program (more or less).  any `GPREL` relocs that show up in the ELF are then rewritten against this link-time constant.  is that correct ?  hopefully it has no relation to the [GOT](https://en.wikipedia.org/wiki/Global_Offset_Table).

there's the question of whether `GPREL` relocs are used in FLAT programs, but if it doesn't take much effort to support them, and you really want it, we can figure it out.

i'm assuming `__global_pointer$` only needs to be available to the runtime loader, not to the static linker.  please correct me if i'm mistaken.

a few ideas off the top of my head:
* use `--defsym` as i mentioned.  i'm guessing you want GP to point somewhere random into the middle of the data to make it easier for GPREL relocs to be small (assuming a signed offset).  you'll need an anchor for that.  we already have `__data_start`, so can you use that ?  `--defsym=__global_pointer$=__data_start+0x800`.  it includes got sections too, but i don't think those will actually contain anything, so shouldn't be a problem ?
* we have support for runtime removal of code from the linker script (see `R_RODAT` and such).  we could add logic for targets so you could use a syntax like `TARGET_riscv64:  __global_pointer$ = ...`.  that should be fairly easily to plumb through since you'll have `TARGET_CPU` available in `ld-elf2flt.c` to expand.
* having `TARGET_xxx` checks in the linker script for runtime processing doesn't feel quite right when none of our other tools are multitarget aware (e.g. build a single ld-elf2flt program that can handle all targets dynamically).  we have support for `@FOO@` replacements in the linker script.  we wouldn't be able to do anything fancy or conditional (due to limitations in the linker script language, and the fact that `TARGET_xxx` is dynamic based on configure's `--target=`), but we could do something akin to GNU ld.  in configure.ac, define something like `AC_SUBST(LDSCRIPT_PRE_RODATA)`, then add a section where that variable is set based on `$target`.  for riscv, you can stuff this `__global_pointer$` in.  but maybe doing the dynamic approach above ultimately ends up being cleaner as the `elf2flt.ld.in` file will be easier to read & write since the logic won't be spread across multiple files.

2021-08-20 06:25 UTC, vapier commented on elf2flt.c
> +  if (!load_to_ram)
`-r` is the default.  one would have to explicitly specify options to change this behavior.  i'm inclined to just leave this logic out.  especially since people rarely, if ever, invoke these tools themselves.  instead, they integrate things with their toolchain and it takes care of invoking `elf2flt` and such for them.

2021-08-20 06:25 UTC, vapier commented on elf2flt.c
> +#elif defined(TARGET_riscv64)
should this also cover `TARGET_riscv32` ?  seems pretty easy to add now.

2021-08-20 06:40 UTC, damien-lemoal commented
Mike,

Thanks for the detailed comments. Let me explore your suggestions. The section ordering might be a blocker though. I need to dig a little more on that.

2021-08-20 07:21 UTC, vapier commented
glancing through `ld-elf2flt.c`, we already do this sort of thing it seems.  for shared libs, we use `-defsym` to set up symbols based on the target.  the runtime uses these symbols to initialize specific registers (e.g. Blackfin's loader will set the P5 register to `_current_shared_library_p5_offset_`).  if my understanding of `__global_pointer$` & the riscv GP register is correct, then this style would be aligned.

```
        /* Provide the symbol specifying the library's data segment
           pointer offset.  */
        adj = 4;
        if (streq(TARGET_CPU, "h8300"))
            got_offset = "__current_shared_library_er5_offset_";
        else if (streq(TARGET_CPU, "bfin"))
            got_offset = "_current_shared_library_p5_offset_", adj = 1;
        else
            got_offset = "_current_shared_library_a5_offset_";
        append_option(&other_options, "-defsym");
```

wrt section ordering, i'd be fine doing a partial merge.  i.e. have your PR only update `elf2flt.c` (the new `TARGET_riscv` settings) & `ld-elf2flt` (for `__global_pointer$` define) & perhaps `elf2flt.ld.in` (if you really need to define a new symbol to base off of in case the existing `__data_start` is insufficient).  that would at least reduce the size of your out-of-tree patch.

oh, and we should make sure to extend test coverage.  but that might need to be a sep PR.  you'll need to:
* update travis/arches.sh in this repo to include riscv targets
* update https://github.com/uclinux-dev/prebuilts-binutils-libs to output riscv's elf.h
* we might need to refresh or get a newer version of binutils prebuilts to make this happen ... which comes with its own set of issues (see #14)

2021-09-02 09:01 UTC, damien-lemoal commented
I sent a new pull request against the main branch (as I previously was working against "master"). Closing this request as I could not figure out how to update it :)

2021-09-02 09:01 UTC, closed without merging